GET http://localhost:9090/clothingItem/all
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoidXNlcjVAZ21haWwuY29tIiwiZXhwIjoxNjA2MzY0NzIyfQ.8GWCEGzGBDwjatn2QH80omYbUSbTA93bsxoy1UMjjzQ