GET http://localhost:9090/clothingItem/top-ten
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoidXNlcjFAZ21haWwuY29tIiwiZXhwIjoxNjA2MTk5NjU5fQ.dyrBqVoeYYNCY92FFXYXf50iXFMNXgpkTQSJ5diMILk