GET http://localhost:9090/user
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoidXNlcjFAZ21haWwuY29tIiwiZXhwIjoxNjA2MTIzNzQ4fQ.nYKmB_QH0ZLpB74D5l9xaXmR8U-a_a8p5OemvcAklc0

{
"email": "user1@gmail.com",
"password": "12345",
}

###
