POST http://localhost:9090/user/signup
Content-Type: application/json

{
"email": "heyothisisatestemail@emailplace.email",
  "username": "iamauserthisismyname",
  "password": "riderspassword",
  "zipcode": 85202,
  "gender": "Male"
}

###
